basic_settings:
  site_title: Three Key Therapy
  favicon_image: /images/favicon-mahogony.png

header_settings:
  logo_image: /images/logomahogony0.svg
  logo_width: 250

menu_settings:
  menu_items:
    - title: 'Individual Sessions'
      url: '/bodytherapy'
    - title: 'Workshops'
      url: '/workshops/'
    - title: 'Testimonials'
      url: '/testimonials'        
    - title: 'Pricing'
      url: '/pricing'           
    - title: 'About'
      url: '/about'
    - title: <a href="/contact" class="button button--small"><b>Book now</b></a>
      url: '/contact'

footer_settings:
  footer_tagline:

hero_settings:
  overlay_opacity: 0.6

post_settings:
  grid_spacing: 10

contact_settings:
  form_action: 'https://formspree.io/f/xjvqlzav'
  confirmation_url: '/thanks'
  email_subject: 'Three Key Therapy - Thank you for reaching out'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: ''
  twitter_url: ''
  instagram_url: ''
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: ''

color_settings:
  background_color: '#FAF6DB'
  background_alt_color: '#FFCD7E'
  text_dark_color: '#7A1502'
  text_medium_color: '#5d6976'
  text_light_color: '#6C7A89'
  accent_color: '#D55A1F'
  border_color: '#7A1502'
  hero_background_color: '#7A1502'
  hero_text_color: '#FAF6DB'
  error_color: '#7A1502'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Muli:300,400,600,700" rel="stylesheet">'
  title_font: '"Muli", sans-serif'
  body_font: '"Muli", sans-serif'
  regular_weight: 400
  bold_weight: 600
  site_title:
    small_size: 25
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
  menu:
    small_size: 30
    medium_size: 15
    large_size: 17
    weight: 600
    letter_spacing: 0
  h1:
    small_size: 35
    medium_size: 45
    large_size: 60
    weight: 700
    letter_spacing: -0.03
    line_height: 1.2
  h2:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 600
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 18
    medium_size: 20
    large_size: 22
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""
